### ISSUE TITLE
version could not be resolved (missing /root/.tfenv/version)

### ISSUE THREAD

**Issue by marekaf** [seqsense/terraform-lock-fix-action#14]
Hi, I'm getting this error when using the example in Readme.MD

### Description

```
Setting up authentication
Updating
Installing Terraform v1.2.2
Downloading release tarball from https://releases.hashicorp.com/terraform/1.2.2/terraform_1.2.2_linux_amd64.zip
####################################################                      73.3%
######################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.2.2/terraform_1.2.2_SHA256SUMS
No keybase install found, skipping OpenPGP signature verification
terraform_1.2.2_linux_amd64.zip: OK
Archive:  /tmp/tfenv_download.feifEc/terraform_1.2.2_linux_amd64.zip
  inflating: terraform
Installation of terraform v1.2.2 successful. To make this your default version, run 'tfenv use 1.2.2'
cat: can't open '/root/.tfenv/version': No such file or directory
Version could not be resolved (set by /root/.tfenv/version or tfenv use <version>)
```

### Steps to Reproduce

1. copy-paste of the example in readme.md

### Your Environment

Any idea what's wrong?
Seems like tfenv installs the correct version but can't detect its persistence afterwards.

**Comment by marekaf** [comment]
I fixed it with this workaround:
```
    env:
       TFENV_TERRAFORM_VERSION: 1.2.2
```

**Comment by kamatama41** [comment]
Thank you for reporting this issue 😃 
This error is due to a lack of consideration in the case of no version specification on a project.
I will fix the error, but I recommend to specify Terraform version which is used on your project by setting the env variable `TFENV_TERRAFORM_VERSION` or putting `.terraform-version` file on your project (see https://github.com/tfutils/tfenv#terraform-version) because using different Terraform version on a single project might cause inconsistencies of state.
If no version is specified, this action (= tfenv) will always use the latest Terraform version.

**Comment by kamatama41** [comment]
@marekaf 
The error has been fixed, please retry your CI build, thanks.
